### ISSUE TITLE
the role is always rebooting the system

### ISSUE THREAD

**Issue by Mumie-hub** [robertdebock/ansible-role-reboot#1]
**Describe the bug**
the robertdebock.reboot role is always rebooting the server (ubuntu 18.04). I bootstrapped with the robertdebock.bootstrap role also.
I tested with a clean install of ubuntu. i think the Problem is the command, checking if a reboot is required:  ansible-role-reboot/tasks/main.yml  Task:
`- name: see if a reboot is required;  
  command: needs-restarting -r`

needs-restarting package is not present on my system (not installed with the common and preview packages in the bootstrap role).

**Expected behavior**
not rebooting the server if its not required.

**Environment**
- Control node OS: fedora 29
- Control node Ansible version: 2.8.2
- Managed node OS: ubuntu 18.04.3

**Additional context**
iam quiet new to ansible, sorry if iam mistaken here.
Best regards

**Comment by robertdebock** [comment]
Thanks for the contribution, I'll try to reproduce and write a fix.

**Comment by linuxmail** [comment]
hi,

same for [me](https://github.com/robertdebock/ansible-role-update/issues/16) :-) I changed the task a bit. 

```yaml
---
# tasks file for reboot

- name: Check Debian for require reboot
  stat:
    path: /var/run/reboot-required
  register: file_reboot_required
  when:
    - ( ansible_distribution == "Debian" 
      or ansible_virtualization_type != "docker" )

- name: Check for needs_restarting
  stat:
    path: /usr/bin/needs-restarting
  register: file_needs_restarting
  when:
    - (ansible_pkg_mgr == "yum" or
      ansible_pkg_mgr == "dnf" ) or 
      ansible_virtualization_type != "docker"


- name: Check for require reboot RedHat based
  command: needs-restarting -r
  register: needsrestarting
  changed_when:
    - needsrestarting.rc != 0
  failed_when:
    - needsrestarting.rc != 1
    - needsrestarting.rc != 0
  when:
    - file_needs_restarting.stat.exists

- name: flush handlers
  meta: flush_handlers

- name: reboot the machine
  shell: "(sleep {{ reboot_delay }} && {{ reboot_command }} &)"
  async: 1
  poll: 0
  ignore_errors: no
  when:
    - ansible_virtualization_type != "docker"
    - file_reboot_required.stat.exists
    - file_needs_restarting.stat.exists and needsrestarting.changed

  notify:
    - 1 wait for the start of reboot
    - 2 wait for the machine to be up
    - 3 gather facts after reboot
  tags:
    - skip_ansible_lint

- name: flush handlers
  meta: flush_handlers
```

It may breaks RPM based systems, so a bit fine tuning is required.
