### ISSUE TITLE
Setting reboot_always to yes does not have the intended effect

### ISSUE THREAD

**Issue by cjsteel** [robertdebock/ansible-role-reboot#4]
**Describe the bug**
The task "reboot the machine" does not cause a reboot for non Docker containers, VM's or bare metal  when the `defaults/main.yml` var `reboot_always` is set to yes.

**Test Playbook**

```yaml
---
- name: Force Reboot of non docker container, VM or physical system
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    - reboot_always: yes
  roles:
    - robertdebock.reboot
```

**Output**

```shell
TASK [robertdebock.reboot : reboot the machine] *************************************************************************************************************************************
skipping: [node0]
skipping: [node1]
skipping: [node2]
skipping: [node3]
skipping: [node4]
```

**Expected behavior**
All non docker containers, VM's and bare metal should be rebooted

**Proposed adjustment**

Here is the task with the additional `or` rule which allows the reboot_always variable to always reboot non docker containers, VM's and metal and so on.

```yaml
- name: reboot the machine
  shell: "(sleep {{ reboot_delay }} && {{ reboot_command }} &)"
  async: 1
  poll: 0
  ignore_errors: yes
  when:
    - ansible_virtualization_type != "docker"
    - (reboot_check_for_needs_restarting_for_rhel.stat.exists and
      needsrestarting.rc == 1) or
      reboot_check_for_needs_restarting_for_debian.stat.exists or
      reboot_always
  notify:
    - 1 wait for the start of reboot
    - 2 wait for the machine to be up
    - 3 gather facts after reboot
``` 
**Output after adjustment to task**

```shell
TASK [robertdebock.reboot : reboot the machine] *************************************************************************************************************************************
changed: [node4]
changed: [node1]
changed: [node0]
changed: [node2]
changed: [node3]

RUNNING HANDLER [robertdebock.reboot : 1 wait for the start of reboot] **************************************************************************************************************
Pausing for 4 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [node4]

RUNNING HANDLER [robertdebock.reboot : 2 wait for the machine to be up] *************************************************************************************************************
ok: [node0]
ok: [node1]
ok: [node2]
ok: [node3]
ok: [node4]

RUNNING HANDLER [robertdebock.reboot : 3 gather facts after reboot] *****************************************************************************************************************
ok: [node4]
ok: [node0]
ok: [node2]
ok: [node3]
ok: [node1]
```
